### ISSUE TITLE
请求大佬分享一下随机图的源码，想调用自己的随机图API。

### ISSUE THREAD

**Issue by Swor-dart** [anosu/alist-style#1]
请求大佬分享一下**随机图的源码和使用方法**，想把自己的图片也区分pc和mp来显示，非常感谢！

**Comment by anosu** [comment]
> 请求大佬分享一下**随机图的源码和使用方法**，想把自己的图片也区分pc和mp来显示，非常感谢！

https://github.com/anosu/shuffle-img-api

**Comment by Swor-dart** [comment]
> > 请求大佬分享一下**随机图的源码和使用方法**，想把自己的图片也区分pc和mp来显示，非常感谢！
> 
> https://github.com/anosu/shuffle-img-api

感谢！

**Comment by Swor-dart** [comment]
> 
感谢！

**Comment by Swor-dart** [comment]
> > 请求大佬分享一下**随机图的源码和使用方法**，想把自己的图片也区分pc和mp来显示，非常感谢！
> 
> https://github.com/anosu/shuffle-img-api

感谢！
