### ISSUE TITLE
大佬有考虑适配最新版v3.31吗

### ISSUE THREAD

**Issue by devnakx** [anosu/alist-style#3]
![1](https://github.com/anosu/alist-style/assets/38558065/55781214-0ba9-4ead-97e3-72ef89217fcc)
因为最新3.31好像有bug，原本的导航栏不透明了，而且上面也多了一个白条

**Comment by anosu** [comment]
> ![1](https://private-user-images.githubusercontent.com/38558065/307413544-55781214-0ba9-4ead-97e3-72ef89217fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NjU0MTksIm5iZiI6MTcwODc2NTExOSwicGF0aCI6Ii8zODU1ODA2NS8zMDc0MTM1NDQtNTU3ODEyMTQtMGJhOS00ZWFkLTk3ZTMtNzJlZjg5MjE3ZmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDA4NTgzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkMGVlYjU4ZWM3MDQ2YzY0Y2VjZTVmYTkyOTRmZTE3MDQ0ODZmMWNmYzExNDcxNzQ1ZmRjYTczN2FiMjczNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.docAaIi_M4SPfHSFsWjTIitdWtD0kmJT1QGvbxOona4) 因为最新3.31好像有bug，原本的导航栏不透明了，而且上面也多了一个白条

已经改了，试试现在还有问题吗

**Comment by devnakx** [comment]
刚刚用源代码试了下已经没问题了，等国内CDN刷新就好了
